### ISSUE TITLE
Setup issues, cannot get it working with latest wordpress

### ISSUE THREAD

**Issue by Rhyspacker** [iantsch/wp-hbs-engine#1]
Hi Iantch, 

I was wondering if this is still maintained to work with the latest wp?

I followed the installation instructions, and even did a composer install in the plugin folder. But upon calling the_hbs-template() it simply doesn't render anything. I placed .hbs files in my theme-folder/src/templates too but nothing.  

Maybe I'm overlooking something here, be great to get your advice as would be ideal to get this working. 

Thanks,
Rhys.

**Comment by iantsch** [comment]
Haven't checked yet. I will have a look and come back to you with an answer.

Do you manage all your php dependencies with composer?

**Edit**: I might have forgotten to put some Infos in the readme 🤦‍♂️

**Comment by Rhyspacker** [comment]
Okay no worries, and yeah I use composer for dependencies but maybe I haven't set it up properly. I'll wait for you to add info as that might help, if you get the chance to. I've managed to get Mustache working in my project but I prefer Handlebars as I'm familiar.

**Comment by iantsch** [comment]
Ok, found some time to check it out.

Good news, it works. I found a minor bug and extended the readme.

I created a gist, but it is basically the example code from the readme:
https://gist.github.com/iantsch/0fd07b67022484d6d7b508c001f449f5

**Comment by iantsch** [comment]
Created #2 to make activation of plugin easier in the future.
